name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Build and run Docker container (Staging)
      run: |
        docker build -t cidadesinteligentes:staging .
        docker run -d -p 8080:80 cidadesinteligentes:staging

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Build and run Docker container (Production)
      run: |
        docker build -t cidadesinteligentes:production .
        docker run -d -p 8081:80 cidadesinteligentes:production
